
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Nov 05 21:58:09 CET 2023
//----------------------------------------------------

package mjparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 19;
  public static final int DIVIDE = 24;
  public static final int LBRACKET = 43;
  public static final int INCREMENT = 35;
  public static final int CONST = 6;
  public static final int PERIOD = 40;
  public static final int NOT_EQUAL = 27;
  public static final int LPAREN = 41;
  public static final int SEMI = 37;
  public static final int GREATER = 28;
  public static final int CONTINUE = 15;
  public static final int NUM_CONST = 18;
  public static final int DECREMENT = 36;
  public static final int LESS = 30;
  public static final int MINUS = 22;
  public static final int RPAREN = 42;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int LESS_EQUAL = 31;
  public static final int PLUS = 21;
  public static final int MULTIPLY = 23;
  public static final int ASSIGN = 34;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 44;
  public static final int EQUAL = 26;
  public static final int GREATER_EQUAL = 29;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MODULO = 25;
  public static final int BREAK = 3;
  public static final int IDENT = 17;
  public static final int VOID = 13;
  public static final int ARROW = 47;
  public static final int COLON = 38;
  public static final int FOREACH = 16;
  public static final int LBRACE = 45;
  public static final int ELSE = 5;
  public static final int READ = 11;
  public static final int WHILE = 8;
  public static final int RBRACE = 46;
  public static final int EXTENDS = 14;
  public static final int BOOL_CONST = 20;
  public static final int PRINT = 10;
}

